# Stats Causal

https://analyticsindiamag.com/a-complete-guide-to-causal-inference-in-python/

In [11]:
import warnings
warnings.filterwarnings('ignore')

In [12]:
%matplotlib inline

In [13]:
import matplotlib.pyplot as plt

In [14]:
import matplotlib as mpl
mpl.rcParams['figure.figsize'] = (15, 8)
# mpl.rcParams["figure.dpi"] = dpi
mpl.rc('xtick', labelsize=15) 
mpl.rc('ytick', labelsize=15)

font_size=15
title_font_size=25

In [15]:
import pandas as pd
print(pd.__version__)

1.4.2


In [16]:
import numpy as np

In [141]:
# proba of well dressed
p_z = 0.5

# well dresses
z = np.random.binomial(n=1, p=p_z, size=500)
z.mean(), z.std()

(0.51, 0.4998999899979995)

In [142]:
z

array([0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,

In [143]:
# 
p_x_z = [0.9, 0.1]
p_x = np.choose(z, p_x_z)

# probas of 
p_x

array([0.9, 0.1, 0.1, 0.9, 0.9, 0.1, 0.1, 0.9, 0.9, 0.1, 0.9, 0.9, 0.9,
       0.1, 0.1, 0.9, 0.9, 0.9, 0.1, 0.1, 0.9, 0.1, 0.9, 0.1, 0.9, 0.9,
       0.1, 0.9, 0.9, 0.1, 0.1, 0.1, 0.1, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9,
       0.1, 0.9, 0.9, 0.1, 0.9, 0.1, 0.9, 0.1, 0.1, 0.1, 0.9, 0.1, 0.1,
       0.9, 0.9, 0.9, 0.9, 0.1, 0.9, 0.1, 0.1, 0.9, 0.9, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.9, 0.9, 0.1, 0.1, 0.9, 0.9, 0.9, 0.9, 0.9, 0.1,
       0.1, 0.9, 0.9, 0.1, 0.1, 0.9, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.9, 0.9, 0.1, 0.1, 0.9, 0.9, 0.1, 0.1, 0.1, 0.9, 0.1, 0.1,
       0.9, 0.9, 0.1, 0.9, 0.9, 0.9, 0.1, 0.9, 0.9, 0.9, 0.9, 0.9, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.9, 0.1, 0.1, 0.1, 0.1, 0.9, 0.9,
       0.9, 0.9, 0.1, 0.1, 0.1, 0.9, 0.9, 0.9, 0.9, 0.9, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.9, 0.9, 0.1, 0.1, 0.1, 0.1, 0.9, 0.9, 0.9, 0.9,
       0.9, 0.1, 0.1, 0.1, 0.9, 0.1, 0.1, 0.1, 0.1, 0.9, 0.9, 0.9, 0.9,
       0.9, 0.1, 0.9, 0.1, 0.9, 0.9, 0.9, 0.1, 0.1, 0.1, 0.1, 0.

In [144]:
x = np.random.binomial(n=1, p=p_x, size=500)
x.mean(), x.std()

(0.488, 0.4998559792580259)

In [145]:
x

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,

In [116]:
index = x+2*z
index

array([2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 3, 2, 2, 0, 1, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 3, 2, 1, 1, 1,
       1, 2, 2, 1, 2, 0, 2, 2, 0, 0, 2, 2, 1, 2, 2, 1, 1, 1, 3, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 3, 3, 2,
       1, 3, 2, 1, 2, 0, 1, 1, 2, 0, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1,
       2, 1, 1, 3, 1, 0, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1,
       1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 3, 1, 1, 1, 2,
       1, 1, 3, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 0, 2, 2, 2, 2, 1, 1,
       1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 2, 3, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2,
       1, 2, 3, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 3, 1, 2, 1, 1,
       0, 2, 3, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 3, 1, 2, 2,
       2, 2, 1, 1, 1, 2, 1, 2, 1, 0, 0, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2,
       2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1,
       2, 2, 2, 2, 2, 1, 2, 1, 1, 0, 1, 2, 0, 1, 1,

In [113]:
p_y_xz = [0.2, 0.4, 0.6, 0.8]
p_y = np.choose(index, p_y_xz)
p_y

array([0.6, 0.6, 0.6, 0.4, 0.6, 0.6, 0.6, 0.6, 0.6, 0.4, 0.4, 0.4, 0.6,
       0.4, 0.6, 0.6, 0.6, 0.4, 0.4, 0.6, 0.4, 0.2, 0.4, 0.4, 0.6, 0.4,
       0.4, 0.4, 0.6, 0.4, 0.6, 0.4, 0.6, 0.4, 0.4, 0.6, 0.4, 0.4, 0.4,
       0.6, 0.6, 0.4, 0.4, 0.4, 0.4, 0.6, 0.6, 0.4, 0.6, 0.4, 0.6, 0.6,
       0.4, 0.4, 0.6, 0.6, 0.4, 0.6, 0.6, 0.4, 0.4, 0.4, 0.6, 0.6, 0.4,
       0.4, 0.4, 0.4, 0.6, 0.4, 0.4, 0.4, 0.4, 0.4, 0.2, 0.4, 0.6, 0.8,
       0.6, 0.4, 0.4, 0.6, 0.6, 0.4, 0.2, 0.8, 0.6, 0.6, 0.4, 0.6, 0.6,
       0.4, 0.6, 0.4, 0.4, 0.4, 0.6, 0.4, 0.6, 0.4, 0.6, 0.4, 0.6, 0.6,
       0.8, 0.6, 0.4, 0.6, 0.4, 0.4, 0.6, 0.2, 0.4, 0.6, 0.4, 0.4, 0.4,
       0.2, 0.4, 0.6, 0.6, 0.8, 0.2, 0.4, 0.6, 0.6, 0.6, 0.6, 0.4, 0.6,
       0.6, 0.4, 0.4, 0.6, 0.6, 0.6, 0.4, 0.4, 0.6, 0.6, 0.2, 0.6, 0.6,
       0.6, 0.4, 0.4, 0.4, 0.6, 0.6, 0.6, 0.4, 0.4, 0.4, 0.6, 0.4, 0.4,
       0.6, 0.2, 0.2, 0.6, 0.4, 0.4, 0.6, 0.6, 0.4, 0.6, 0.6, 0.2, 0.4,
       0.4, 0.6, 0.6, 0.6, 0.6, 0.4, 0.4, 0.4, 0.4, 0.8, 0.4, 0.

In [117]:
y = np.random.binomial(n=1, p=p_y, size=500)
y

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,

In [137]:
# x: properly dressed
# y: productive

generate_dataset_0 = pd.DataFrame({"x":x, "y":y, "z":z})
generate_dataset_0.describe()

x           y         z
count  500.000000  500.000000  500.0000
mean     0.518000    0.530000    0.4800
std      0.500176    0.499599    0.5001
min      0.000000    0.000000    0.0000
25%      0.000000    0.000000    0.0000
50%      1.000000    1.000000    0.0000
75%      1.000000    1.000000    1.0000
max      1.000000    1.000000    1.0000

In [138]:
ds = generate_dataset_0
ds

x  y  z
0    0  1  1
1    0  1  1
2    0  0  1
3    1  1  0
4    0  1  1
..  .. .. ..
495  1  1  0
496  1  0  0
497  0  1  1
498  0  0  1
499  0  1  1

[500 rows x 3 columns]

In [132]:
ds_not_proper = ds[ds.x == 0]
ds_not_proper.count()

x    241
y    241
dtype: int64

In [146]:
ds_not_proper.y.sum(), ds_not_proper.y.mean()

(156, 0.6473029045643154)

In [134]:
ds_proper = ds[ds.x == 1]
ds_proper.count()

x    259
y    259
dtype: int64

In [149]:
ds_proper.y.sum(), ds_proper.y.mean()

(109, 0.42084942084942084)

In [148]:
def estimate_uplift(ds):
    base = ds[ds.x == 0]
    variant = ds[ds.x == 1]
    delta = variant.y.mean() - base.y.mean()
    delta_err = 1.96 * np.sqrt(
        variant.y.var() / variant.shape[0] + 
        base.y.var() / base.shape[0])
    return {"estimated_effect": delta, "standard_error": delta_err}
estimate_uplift(generate_dataset_0)

{'estimated_effect': -0.22645348371489454,
 'standard_error': 0.08534371508162718}